[package]
name = "rust_crate"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
ieee80211 = "0.4.0"

[features]
default = []

[build-dependencies]
bindgen = "0.69.4"
