[toolchain]
# Use "esp" for ESP32, ESP32-S2, and ESP32-S3
# channel = "esp"
# Use "nightly" for ESP32-C*, ESP32-H* targets
# channel = "nightly-2023-08-23"
channel = "nightly"
components = ["rustfmt", "rustc-dev"]
targets = ["riscv32imc-unknown-none-elf"]